server {
    listen 80;
    server_name kittygram-test.mooo.com;

    client_max_body_size 20M;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api/ {
        client_max_body_size 20M;
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static_backend/ {
        alias /usr/share/nginx/html/static_backend/;
    }

    location /media/ {
        alias /usr/share/nginx/html/media/;
    }
}